car:
  maxCars: 3
  sorting:
      power,
      brand
user:
  loan.minimalIncome: 40000
  loan.minCarPrice: 1000000
  loan.coefficientOfCarPrice: 0.3
  loan:
    value-of-month-income: 6
starter-income:
  path: https://66055cd12ca9478ea1801f2e.mockapi.io/api/users/income
spring:
  application:
    name: Cars
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://localhost:5432/cars
    username: postgres
jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL9Dialect